# Generated by Django 4.1.6 on 2023-02-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technologie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "image",
                    models.ImageField(upload_to="portfolio/images/tecnhnologies"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="portfolio/images/projects"),
        ),
    ]
